#cloud-config
autoinstall:
  version: 1
  user-data:
    oem-config:
      enable: true
  storage:
    layout:
      name: lvm  # Adjust this based on your storage preferences
  packages:
    - oem-config-gtk  # Installs the graphical OEM setup package
  late-commands:
    # Enable OEM mode
    - curtin in-target --target=/target -- apt-get install oem-config-gtk -y
    - curtin in-target --target=/target -- systemctl enable oem-config.service
  interactive-sections:
    - oem-config
