#cloud-config
autoinstall:
  version: 1
  locale: en_US  # Set your preferred locale
  keyboard:
    layout: us  # Set your preferred keyboard layout
  network:
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: true  # Configures network with DHCP
  storage:
    layout:
      name: direct  # Direct layout without LVM, adjust as needed
  packages:
    - oem-config-gtk  # Install necessary OEM configuration package
  late-commands:
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get install -y oem-config oem-config-gtk
    - curtin in-target --target=/target -- systemctl enable oem-config.target
    - curtin in-target --target=/target -- systemctl set-default oem-config.target
  interactive-sections:
    - user  # To defer user creation until OEM setup
